18css modal
tisidro/stylewithcss pull request #22
Opened 2022-08-29 02:24 UTC by tisidro

# Description
This is a documentation of learning as I work through a [Zastrow CSS Tutorial](link url here). The CSS is not written by me. It may have some revisions and seem to overlap as I walk through the tutorial process. The key focus areas are listed in Validation below. Here is the [Jira Ticket](https://sparkbox.atlassian.net/browse/FSA22V2-65?atlOrigin=eyJpIjoiNjEzOGY5NzExODE5NDc1ZDliOTFkYWFiZjVkNzk1NTQiLCJwIjoiaiJ9) to give more details and info! :)
## Validation
- [ ]  Code is proofread.
- [ ]  Comments are relevant/well written.
- [ ]  Documents are formatted.
- [ ]  Commit messages are appropriate  and "tell a story" of how the code was written.
Thank you for helping with my progress in Github workflow and CSS mastery! :)

2022-08-29 16:00 UTC, theogainey requested changes
Took a look at your commit history and I was very pleased to see that you have done a great job a keeping a linear commit history. All that practice will pay off in the future. One thing I would like you to think about is your commit `fix: links missing from head tag`. Does this commit represent a fix to the repository as it existed before this PR or does it represent a fix to a mistake you made while working on this PR? If it does not represent a fix to the repository as it existed before this PR you might want to consider handling it differently.

2022-08-29 16:00 UTC, theogainey commented on 18css-modal/index.html
> +        <section class="modal">
Lines 47 and 48 you have HTML elements that do not have a matching closing Tag
```
<div id="disclaimer" class="modal-container">
<section class="modal">
```
A good way to check for this is by putting your code into an HTML validator. Here is a good one [https://validator.w3.org/](https://validator.w3.org/).

2022-08-29 16:00 UTC, theogainey commented on 18css-modal/README.md
> +```
Nice use of bullet points, inline code blocks, and regular code blocks. This makes the README very easy to follow

2022-08-29 16:53 UTC, tisidro commented on 18css-modal/index.html
> +        <section class="modal">
Thanks, I made the changes and will re-request review. If you approve I'll finish this up. :)

2022-08-29 16:56 UTC, tisidro commented on 18css-modal/index.html
> +        <section class="modal">
Here's the sha for the fix commit: 8c85ab256275da5ead605a83189684e4995d393e

2022-08-29 16:59 UTC, tisidro commented on 18css-modal/index.html
> +        <section class="modal">
Also, that fix was something I realized was missing after I had committed that section and was now working on a new section. Last time I did this I was working w/ Rise and she said not to group catching an error in with an unrelated commit where I was working on something specific--but to make its own commit (which I can remove later during squash but it will still "be there").

Is there another way to handle I should think about--please lmk! :)

2022-08-29 17:06 UTC, theogainey commented on 18css-modal/index.html
> +        <section class="modal">
Rise is correct. For how to handle this think back to our pairing last week. During that paring we used an interactive rebase to stop on a specific commit and then we amended that commit.  Thats what you should do here. Start a rebase, tell git that you want to stop at the commit you made the error at, amend that commit with your fix, tell git to continue the rebase, then you can drop the `fix: missing HTML tags` commit.

2022-08-29 17:19 UTC, tisidro commented on 18css-modal/index.html
> +        <section class="modal">
Ok, I am unbelievably less afraid to do that today! :) I'll drop you a note when I do it --probably around 2.

2022-08-31 15:29 UTC, theogainey approved these changes
![](https://media3.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e476iumevnrlbjxs0ibaqjj6to57pl4ui8nxcfct90a&rid=giphy.gif&ct=g)

2022-08-31 15:48 UTC, merged